import React, { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowUpRight, ArrowRight, ArrowLeft, Plus, Users, Globe2, Images, Search, Check, X, Copy, UploadCloud, Sparkles, FileImage, CheckCircle2, Loader2, Menu, FolderOpen, ExternalLink, Save, Info, Bell, Settings } from 'lucide-react';
import './reference.css';

const CRITERIA = ['Critical Role','Media Coverage','Key Position','Commercial Success','Recommendation Letters','High Salary'];
const criterionLabel = c => ({'Critical Role':'重要演出或参与','Media Coverage':'媒体报道','Key Position':'关键职位','Commercial Success':'商业成绩','Recommendation Letters':'推荐信','High Salary':'高薪证明','All evidence':'全部材料'}[c] || c);
const criterionNotes = ['主要或重要参与经历','关于申请人工作的公开报道','在机构中承担的重要职责','有材料支持的商业成绩','行业专家提供的推荐','专业工作的薪酬材料'];
async function request(url, data, method='POST') {const r=await fetch(url,data?{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}:{});const result=await r.json();if(!r.ok)throw new Error(result.error||'操作失败，请重试。');return result;}
const initials = name => name.split(' ').map(x=>x[0]).slice(0,2).join('');
const dateLabel = value => new Date(value).toLocaleDateString('zh-CN',{month:'short',day:'numeric',year:'numeric'});

function App(){
  const [state,setState]=useState({applicants:[],evidence:[],services:{ai:'demo',storage:'local'}});
  const [route,setRoute]=useState(location.hash.slice(1)||'applicants');
  const [selected,setSelected]=useState('');
  const [search,setSearch]=useState('');
  const [createOpen,setCreateOpen]=useState(false);
  const [toast,setToast]=useState(null);
  const [mobileOpen,setMobileOpen]=useState(false);
  const [loading,setLoading]=useState(true);
  const [error,setError]=useState('');
  const [batch,setBatch]=useState([]);
  const [activeImage,setActiveImage]=useState('');
  const [shot,setShot]=useState(null);
  const [detailFilter,setDetailFilter]=useState('All evidence');
  const [editing,setEditing]=useState(null);
  const [infoOpen,setInfoOpen]=useState('');
  const toastTimer=useRef();
  function notify(message,type='success'){setToast({message,type});clearTimeout(toastTimer.current);toastTimer.current=setTimeout(()=>setToast(null),5000);}
  async function refresh(){try{setState(await request('/api/state'));setError('');}catch(e){setError(e.message);}finally{setLoading(false);}}
  useEffect(()=>{refresh();const handler=()=>{setRoute(location.hash.slice(1)||'applicants');setMobileOpen(false);};window.addEventListener('hashchange',handler);return()=>window.removeEventListener('hashchange',handler);},[]);
  function go(next){location.hash=next;setRoute(next);setMobileOpen(false);window.scrollTo(0,0);}
  const applicant=state.applicants.find(a=>a.id===selected);
  const detailId=route.startsWith('applicant/')?route.split('/')[1]:null;
  const detail=state.applicants.find(a=>a.id===detailId);
  const pageName=route==='screenshot'?'网页截图':route==='description'?'图片描述':detail?'申请人档案':'申请人';
  function openApplicant(a){setSelected(a.id);setDetailFilter('All evidence');go('applicant/'+a.id);}
  function chooseApplicant(id){setSelected(id);setBatch([]);setActiveImage('');setShot(null);}
  function toolFor(a,target){if(selected!==a.id)chooseApplicant(a.id);go(target);}
  async function deleteApplicant(a){if(!window.confirm('确定删除申请人“'+a.name+'”及其全部图片和描述吗？删除后无法恢复。'))return;try{await request('/api/applicants',{id:a.id},'DELETE');if(selected===a.id)chooseApplicant('');setEditing(null);await refresh();go('applicants');notify('申请人及全部材料已删除。');}catch(e){notify(e.message,'error');}}
  async function deleteEvidence(e){if(!window.confirm('确定删除这张图片及其已保存的描述吗？删除后无法恢复。'))return false;try{await request('/api/evidence',{id:e.id},'DELETE');setBatch(items=>items.filter(i=>i.savedId!==e.id));setEditing(null);await refresh();notify('图片及描述已删除。');return true;}catch(e){notify(e.message,'error');return false;}}
  const shared={deleteApplicant,deleteEvidence,state,applicant,selected,chooseApplicant,notify,refresh,setState};
  return <div className="app-shell">
    <aside className={'sidebar '+(mobileOpen?'open':'')}>
      <a className="brand" href="#applicants" onClick={()=>setMobileOpen(false)}><span>签证材料助手<small>材料工作台</small></span></a>
      <nav><button className={route.startsWith('applicant')?'active':''} onClick={()=>go('applicants')}><Users size={18}/>申请人</button>
      <button className={route==='screenshot'?'active':''} onClick={()=>go('screenshot')}><Globe2 size={19}/>网页截图</button>
      <button className={route==='description'?'active':''} onClick={()=>go('description')}><Images size={19}/>图片描述</button></nav>
    </aside>
    {mobileOpen&&<div className="scrim" onClick={()=>setMobileOpen(false)}/>}
    <div className="main-shell"><header className="topbar"><button className="icon-button mobile-menu" aria-label="展开菜单" onClick={()=>setMobileOpen(!mobileOpen)}><Menu size={20}/></button><a className="topbar-brand" href="#applicants">签证材料助手</a><div className="top-right"><button className="icon-button" aria-label="通知" onClick={()=>setInfoOpen('notifications')}><Bell size={20}/></button><button className="icon-button" aria-label="设置" onClick={()=>setInfoOpen('settings')}><Settings size={20}/></button><span className="avatar tiny">JW</span></div></header>
    <main>
      {error&&<div className="alert error">{error}<button onClick={refresh}>重试</button></div>}
      {loading?<div className="loading-page"><Loader2 className="spin"/>正在打开工作区…</div>:<>
      {route==='applicants'&&<>
        <div className="page-heading"><h1>申请人</h1><button className="button primary" onClick={()=>setCreateOpen(true)}>新建申请人</button></div>
        <div className="applicants-search search-input"><Search size={18}/><input aria-label="搜索申请人" placeholder="搜索申请人..." value={search} onChange={e=>setSearch(e.target.value)}/></div>
        <section className="panel applicants-panel"><div className="table-scroll"><table><thead><tr><th>姓名</th><th>签证类型</th><th>职业</th><th>操作</th></tr></thead><tbody>{state.applicants.filter(a=>(a.name+' '+a.occupation).toLowerCase().includes(search.toLowerCase())).map(a=><tr key={a.id} onClick={()=>openApplicant(a)}><td><button className="person-link" onClick={e=>{e.stopPropagation();openApplicant(a);}}>{a.name}</button></td><td>{a.visaType}</td><td>{a.occupation}</td><td><button className="text-button danger" onClick={e=>{e.stopPropagation();deleteApplicant(a);}}>删除</button></td></tr>)}</tbody></table></div>{!state.applicants.some(a=>(a.name+' '+a.occupation).toLowerCase().includes(search.toLowerCase()))&&<div className="empty-state"><Search/><h3>没有匹配的申请人</h3><p>请尝试其他姓名或职业。</p></div>}</section>
      </>}
      {detail&&<ApplicantDetail {...shared} detail={detail} filter={detailFilter} setFilter={setDetailFilter} go={go} toolFor={toolFor} onEdit={setEditing}/>}
      {route==='screenshot'&&<ScreenshotPage {...shared} go={go} shot={shot} setShot={setShot} onSend={()=>{if(batch.some(i=>i.id===shot.id)){setActiveImage(shot.id);go('description');return;}if(batch.length>=10){notify('当前已有 10 张图片，请先删除一张再添加。','error');return;}const next={...shot,criterion:'',applicantInImage:'',context:'',descriptionZh:'',description:'',savedId:null};setBatch(prev=>[...prev,next]);setActiveImage(next.id);go('description');notify('截图已添加，请选择材料类别并补充背景。');}}/>}
      {route==='description'&&<DescriptionPage {...shared} batch={batch} setBatch={setBatch} activeImage={activeImage} setActiveImage={setActiveImage} go={go}/>}
      {route!=='applicants'&&route!=='screenshot'&&route!=='description'&&!detail&&<div className="empty-state"><FolderOpen/><h2>找不到该申请人</h2><button className="button" onClick={()=>go('applicants')}>返回申请人列表</button></div>}
      </>}
    </main></div>
    {createOpen&&<CreateApplicant onClose={()=>setCreateOpen(false)} onCreate={async a=>{const created=await request('/api/applicants',a);await refresh();setCreateOpen(false);openApplicant(created);notify('申请人已创建。');}}/>}
    {editing&&<EvidenceEditor evidence={editing} onClose={()=>setEditing(null)} onSaved={async()=>{await refresh();notify('材料修改已保存。');}} notify={notify}/>}
    {infoOpen&&<Modal title={infoOpen==='settings'?'工作区设置':'通知'} onClose={()=>setInfoOpen('')}><div className="info-content">{infoOpen==='settings'?<><p><strong>保存位置</strong><span>保存在这台电脑上</span></p><p><strong>图片描述服务</strong><span>{state.services.ai==='connected'?'已配置':'演示模式，尚未配置 AI'}</span></p><p><strong>网页截图</strong><span>网页内容截图</span></p></>:<p>暂无新通知。</p>}</div></Modal>}
    {toast&&<div className={'toast '+toast.type} role="status">{toast.type==='error'?<Info size={19}/>:<CheckCircle2 size={19}/>}<span>{toast.message}</span><button aria-label="关闭提示" onClick={()=>setToast(null)}><X size={16}/></button></div>}
  </div>;
}

function Modal({title,onClose,children,wide=false}){const ref=useRef();useEffect(()=>{const prior=document.activeElement;ref.current.showModal();return()=>prior?.focus();},[]);return <dialog ref={ref} className={'modal '+(wide?'wide':'')} on取消={onClose} onClick={e=>{if(e.target===ref.current)onClose();}}><div className="modal-header"><h2>{title}</h2><button className="icon-button" aria-label="关闭窗口" onClick={onClose}><X size={21}/></button></div>{children}</dialog>;}
function CreateApplicant({onClose,onCreate}){const [busy,setBusy]=useState(false);const [error,setError]=useState('');return <Modal title="新建申请人" onClose={onClose}><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const f=new FormData(e.currentTarget);await onCreate(Object.fromEntries(f));}catch(e){setError(e.message);setBusy(false);}}}><p className="modal-intro">填写申请人信息，用于整理材料和生成描述。</p><label>姓名 <span className="required">*</span><input autoFocus required name="name" maxLength={100} placeholder="例如：张三"/></label><label>签证类型 <span className="required">*</span><select name="visaType" defaultValue="O1B"><option>O1B</option><option disabled>O2B</option><option disabled>O3B</option></select></label><label>职业 <span className="required">*</span><input required name="occupation" maxLength={100} placeholder="例如：音乐人、视觉设计师"/></label>{error&&<div className="alert error">{error}</div>}<div className="modal-footer"><button type="button" className="button" onClick={onClose}>取消</button><button disabled={busy} className="button primary">{busy?<Loader2 className="spin" size={17}/>:<Plus size={17}/>}新建申请人</button></div></form></Modal>;}

function ApplicantSelect({state,selected,chooseApplicant,disabled=false}){const a=state.applicants.find(x=>x.id===selected);return <div className="applicant-context"><label className="applicant-select-label">申请人 <span className="required">*</span><select aria-label="申请人" value={selected} onChange={e=>chooseApplicant(e.target.value)} disabled={disabled}><option value="">请选择申请人</option>{state.applicants.map(a=><option key={a.id} value={a.id}>{a.name} ({a.visaType} · {a.occupation})</option>)}</select></label>{a?<div className="context-profile"><span className="avatar small tone-0">{initials(a.name)}</span><span>{a.occupation}<small>{a.visaType} 申请</small></span></div>:<span className="context-hint">选择这份材料所属的申请人。</span>}</div>;}
function ApplicantDetail({state,detail,filter,setFilter,go,toolFor,onEdit,deleteApplicant,deleteEvidence}){
 const all=state.evidence.filter(e=>e.applicantId===detail.id);const items=all.filter(e=>filter==='All evidence'||e.criterion===filter);
 return <><button className="back-link" onClick={()=>go('applicants')}><ArrowLeft size={16}/>返回申请人列表</button><div className="profile-heading"><div className="profile-identity"><span className="avatar large tone-0">{initials(detail.name)}</span><div><div className="eyebrow">申请人档案</div><h1>{detail.name}</h1><div className="profile-meta"><span className="visa-badge">{detail.visaType}</span><span>{detail.occupation}</span><span className="meta-dot"/>创建于 {dateLabel(detail.createdAt)}</div></div></div><div className="button-group"><button className="button danger" onClick={()=>deleteApplicant(detail)}>删除申请人</button><button className="button" onClick={()=>toolFor(detail,'screenshot')}><Globe2 size={16}/>网页截图</button><button className="button primary" onClick={()=>toolFor(detail,'description')}><Plus size={17}/>添加材料</button></div></div>
 <div className="section-heading"><h2>O1B 材料分类</h2><span>已保存 {all.length} 份材料，共 6 类</span></div><div className="criteria-grid">{CRITERIA.map((c,i)=><button key={c} className={'criterion-card '+(filter===c?'selected':'')} onClick={()=>setFilter(filter===c?'All evidence':c)}><div><span className="criterion-number">0{i+1}</span><span className="count-badge">{all.filter(e=>e.criterion===c).length}</span></div><h3>{criterionLabel(c)}</h3><p>{criterionNotes[i]}</p></button>)}</div>
 <section className="panel evidence-panel"><div className="panel-toolbar"><div className="section-title">已保存材料 <span className="count-badge">{all.length}</span></div><select aria-label="筛选已保存材料" className="compact-select" value={filter} onChange={e=>setFilter(e.target.value)}>{['All evidence',...CRITERIA].map(c=><option key={c} value={c}>{criterionLabel(c)}</option>)}</select></div>{items.length?<div className="evidence-grid">{items.map(e=><div className="evidence-wrapper" key={e.id}><button className="image-delete" aria-label={"删除材料："+e.name} title="删除图片及描述" onClick={()=>deleteEvidence(e)}><X size={16}/></button><button className="evidence-card" onClick={()=>onEdit(e)}><div className="evidence-thumb"><img src={e.image} alt={e.name}/><span className="thumb-action">查看和编辑<ArrowUpRight size={15}/></span></div><div className="evidence-card-body"><span className="category-tag">{criterionLabel(e.criterion)}</span><h3>{e.name}</h3><p>{e.descriptionZh || e.description}</p><div className="evidence-card-meta"><span>{e.sourceURL?new URL(e.sourceURL).hostname:'上传的图片'}</span><span>{dateLabel(e.createdAt)}</span></div></div></button></div>)}</div>:<div className="empty-state"><span className="empty-icon"><FolderOpen size={28}/></span><h3>{filter==='All evidence'?'还没有保存材料':'此类别还没有材料'}</h3><p>可以截取网页或上传图片。<br/>检查描述后，将材料保存到申请人档案。</p><button className="button primary" onClick={()=>toolFor(detail,'description')}><Plus size={17}/>添加第一份材料</button><span className="empty-footnote">只有点击保存的材料才会显示在这里。</span></div>}</section></>;
}

function ScreenshotPage({state,selected,chooseApplicant,notify,shot,setShot,onSend,go}){
 const [url,setURL]=useState('');const [size,setSize]=useState('a4');const [width,setWidth]=useState(1200);const [height,setHeight]=useState(900);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [step,setStep]=useState(0);
 useEffect(()=>{if(!busy)return;setStep(0);const t=setInterval(()=>setStep(s=>Math.min(2,s+1)),1800);return()=>clearInterval(t);},[busy]);
 async function capture(sample=false){if(!selected){setError('请先选择申请人。');return;}if(!sample){try{const u=new URL(url);if(!['http:','https:'].includes(u.protocol))throw new Error();}catch{setError('请输入以 https:// 或 http:// 开头的完整链接。');return;}}setError('');setBusy(true);try{setShot(await request('/api/screenshot',{applicantId:selected,url,sample,width:size==='a4'?1200:width,height:size==='a4'?1697:height}));notify('截图已生成。');}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function copyImage(){try{const blob=await(await fetch(shot.image)).blob();await navigator.clipboard.write([new ClipboardItem({'image/png':blob})]);notify('图片已复制。');}catch{notify('复制失败，请允许浏览器访问剪贴板后重试。','error');}}
 return <><div className="page-heading"><div><div className="eyebrow">材料工具</div><h1>网页截图</h1><p>输入网页链接，提取主要内容并生成图片。</p></div><span className="feature-label"><Globe2 size={15}/>网页内容截图</span></div><ApplicantSelect {...{state,selected,chooseApplicant}} disabled={busy}/>
 <div className="screenshot-layout"><section className="panel capture-controls"><div className="panel-section-heading"><span className="step-number">1</span><h2>输入网页链接</h2></div><form onSubmit={e=>{e.preventDefault();capture();}}><label>网页链接 <span className="required">*</span><div className="url-input"><Globe2 size={17}/><input aria-label="网页链接" type="url" placeholder="https://example.com/article" value={url} onChange={e=>setURL(e.target.value)} disabled={busy}/></div></label><p className="field-hint">请填写无需登录即可打开的文章或视频页面链接。</p><label className="size-label">图片尺寸</label><div className="segmented" role="group" aria-label="图片尺寸"><button type="button" className={size==='a4'?'selected':''} onClick={()=>setSize('a4')} disabled={busy}>A4 竖版</button><button type="button" className={size==='custom'?'selected':''} onClick={()=>setSize('custom')} disabled={busy}>自定义</button></div>{size==='custom'?<div className="dimension-fields"><label>宽度（像素）<input aria-label="宽度（像素）" type="number" required min="480" max="1600" value={width} onChange={e=>setWidth(e.target.value)}/></label><span>×</span><label>高度（像素）<input aria-label="高度（像素）" type="number" required min="480" max="2000" value={height} onChange={e=>setHeight(e.target.value)}/></label></div>:<div className="size-caption">1200 × 1697 px <span>固定尺寸</span></div>}{error&&<div className="capture-error"><div className="alert error" role="alert">{error}</div><p>也可以在浏览器打开网页，按 Win + Shift + S 截图，再到「图片描述」按 Ctrl + V 粘贴。</p><button type="button" className="text-button" onClick={()=>go('description')}>去粘贴或上传截图<ArrowRight size={15}/></button></div>}<button className="button primary full-width" disabled={busy||!selected||!url.trim()}>{busy?<Loader2 size={17} className="spin"/>:<Sparkles size={17}/>} {busy?'正在生成截图…':'生成截图'}</button></form><div className="capture-note"><CheckCircle2 size={16}/><div><strong>保留主要内容</strong><p>自动提取正文，尝试去除导航、广告和推荐内容。</p></div></div></section>
 <section className="panel capture-preview"><div className="panel-toolbar"><div className="section-title"><span className="step-number">2</span>图片预览</div>{shot&&!busy&&<span className="ready-badge"><Check size={13}/>已完成</span>}</div><div className={'screenshot-canvas '+(shot?'has-image':'')}>{busy?<div className="capture-loading"><span className="loading-orbit"><Globe2 size={30}/></span><h3>{['正在打开网页','正在提取正文','正在生成图片'][step]}</h3><p>请稍等片刻。</p><div className="progress-track"><span style={{width:[25,58,87][step]+'%'}}/></div></div>:shot?<img className="shot-image" src={shot.image} alt={'网页截图：'+shot.title}/>:<div className="empty-state"><span className="page-outline"><span/><span/><span/><span/></span><h3>这里会显示网页截图</h3><p>生成后可在这里预览，<br/>复制图片，或继续生成图片描述。</p><div className="preview-tags"><span>标题和来源</span><span>正文</span><span>主要图片</span></div></div>}</div>{shot&&!busy&&<><div className="shot-meta"><FileImage size={16}/><div><strong>{shot.name}</strong><span>{shot.width} × {shot.height} px · PNG{shot.sample?' · 演示样例':''}</span></div></div><div className="preview-actions"><button className="button" onClick={copyImage}><Copy size={16}/>复制图片</button><button className="button primary" onClick={onSend}>生成图片描述<ArrowRight size={16}/></button></div></>}</section></div></>;
}

function DescriptionPage({state,applicant,selected,chooseApplicant,notify,refresh,batch,setBatch,activeImage,setActiveImage,go,deleteEvidence}){
 const [busy,setBusy]=useState(false);const [uploading,setUploading]=useState(false);const [saving,setSaving]=useState(false);const [error,setError]=useState('');const [dragging,setDragging]=useState(false);const inputRef=useRef();const uploadLock=useRef(false);
 const current=batch.find(i=>i.id===activeImage)||batch[0];const ready=batch.filter(i=>i.criterion&&i.applicantInImage).length;const generated=batch.filter(i=>i.description).length;
 function patchCurrent(patch){setBatch(items=>items.map(i=>i.id===current.id?{...i,...patch,dirty:true}:i));}
 async function removeImage(item){if(item.savedId){await deleteEvidence({id:item.savedId});return;}if(!window.confirm('确定移除这张图片和未保存的描述吗？'))return;setBatch(items=>items.filter(i=>i.id!==item.id));}
 useEffect(()=>{
   function pasteImage(event){
     const files=Array.from(event.clipboardData?.items||[]).filter(item=>item.kind==='file'&&item.type.startsWith('image/')).map(item=>item.getAsFile()).filter(Boolean);
     if(!files.length)return;
     event.preventDefault();
     if(busy||saving||uploading||uploadLock.current){notify('正在处理图片，请稍后再粘贴。','error');return;}
     upload(files);
   }
   document.addEventListener('paste',pasteImage);
   return()=>document.removeEventListener('paste',pasteImage);
 });
 async function upload(files){if(uploadLock.current||busy||saving)return;if(!selected)return setError('请先选择申请人，再上传图片。');const list=Array.from(files);if(!list.length)return;if(batch.length+list.length>10)return setError('每批最多添加 10 张图片。');if(list.some(f=>!['image/jpeg','image/png','image/webp'].includes(f.type)))return setError('请上传 PNG、JPG 或 WebP 图片。');if(list.some(f=>f.size>8*1024*1024))return setError('每张图片不能超过 8 MB。');setError('');uploadLock.current=true;setUploading(true);try{const added=await Promise.all(list.map(file=>new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>{const img=new Image();img.onload=()=>resolve({id:crypto.randomUUID(),name:file.name,image:reader.result,criterion:'',applicantInImage:'',context:'',descriptionZh:'',description:'',sourceURL:'',savedId:null,dirty:true});img.onerror=()=>reject(new Error(file.name+' 无法读取，请更换图片。'));img.src=reader.result;};reader.onerror=()=>reject(new Error('无法读取 '+file.name));reader.readAsDataURL(file);})));setBatch(items=>[...items,...added]);setActiveImage(added[0].id);notify(`已添加 ${added.length} 张图片，请逐张选择类别并补充背景。`);}catch(e){setError(e.message);}finally{uploadLock.current=false;setUploading(false);if(inputRef.current)inputRef.current.value='';}}
 async function generate(){setError('');if(!selected||!batch.length||ready!==batch.length)return setError('请选择申请人，为每张图片选择类别并回答申请人是否在画面中。');setBusy(true);try{const result=await request('/api/describe',{applicantId:selected,images:batch});setBatch(items=>items.map(item=>{const r=result.results.find(x=>x.id===item.id);return r?.description?{...item,description:r.description,descriptionZh:r.descriptionZh,dirty:true,error:null}:{...item,error:r?.error};}));const failed=result.results.filter(r=>r.error).length;if(failed)setError(`${failed} 张图片生成失败，请切换到对应图片查看原因后重试。`);else notify('中英文描述已生成，请检查后逐张保存。');}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function save(){setSaving(true);try{const saved=await request('/api/evidence',{...current,applicantId:selected},current.savedId?'PUT':'POST');setBatch(items=>items.map(i=>i.id===current.id?{...i,savedId:saved.id,dirty:false}:i));await refresh();notify('材料已保存到 '+applicant.name+' 的档案。');}catch(e){notify(e.message,'error');}finally{setSaving(false);}}
 async function copy(language='en'){try{await navigator.clipboard.writeText(language==='zh'?current.descriptionZh:current.description);notify('描述已复制。');}catch{notify('无法访问剪贴板，请选中文字后手动复制。','error');}}
 return <><div className="page-heading"><div><div className="eyebrow">材料工具</div><h1>图片描述</h1><p>补充图片背景，生成中英文描述，检查后保存。</p></div><span className="feature-label"><Images size={15}/>支持多张图片</span></div><ApplicantSelect {...{state,selected,chooseApplicant}} disabled={busy||saving||uploading}/>
 <section className="panel upload-panel"><div className="upload-heading"><div className="section-title"><span className="step-number">1</span>添加图片</div><span>支持 PNG、JPG、WebP，每张不超过 8 MB</span></div><input ref={inputRef} className="visually-hidden" type="file" multiple accept="image/png,image/jpeg,image/webp" aria-label="上传图片" onChange={e=>upload(e.target.files)} disabled={!selected||busy||uploading}/><button className={'dropzone '+(dragging?'dragging':'')} disabled={!selected||busy||uploading} onClick={()=>inputRef.current.click()} onDragOver={e=>{e.preventDefault();setDragging(true);}} onDragLeave={()=>setDragging(false)} onDrop={e=>{e.preventDefault();setDragging(false);if(!busy&&!uploading)upload(e.dataTransfer.files);}}><span className="upload-icon">{uploading?<Loader2 className="spin" size={23}/>:<UploadCloud size={25}/>}</span><span><strong>{!selected?'请先选择申请人':uploading?'正在添加图片…':'点击上传图片'}{selected&&!uploading&&<em>，也可以拖到这里或按 Ctrl + V 粘贴</em>}</strong><small>{selected?'最多添加 10 张，每张图片分别填写类别和背景。':'图片和描述将保存到所选申请人的档案。'}</small></span>{selected&&<span className="button upload-browse">选择文件</span>}</button><p className="field-hint">先选择申请人。在其他网页按 Win + Shift + S 截图，回到此页按 Ctrl + V 即可添加，无需保存文件。普通文字仍可粘贴到备注中。</p><div className="generation-toolbar"><div>{batch.length?<><strong>{batch.length} 张图片</strong><span>{ready} / {batch.length} 张已完成必填项{generated?' · '+generated+' 张已有描述':''}</span></>:<span>请为每张图片选择材料类别，并回答申请人是否在画面中。</span>}</div><button className="button primary" onClick={generate} disabled={busy||uploading||saving||!batch.length||ready!==batch.length||!selected}>{busy?<Loader2 size={17} className="spin"/>:<Sparkles size={17}/>} {busy?'正在生成中英文描述…':'生成全部图片的中英文描述'}</button></div></section>
 {state.services.ai==='demo'&&<div className="demo-banner"><Info size={16}/><span>演示模式：仅根据备注和网页文字生成草稿，尚未连接 AI 看图。</span></div>}{error&&<div className="alert error" role="alert">{error}</div>}
 {batch.length>0?<><div className="image-tabs" role="tablist" aria-label="已添加图片">{batch.map((item,i)=><div className="image-tab-wrapper" key={item.id}><button role="tab" aria-selected={current?.id===item.id} className={current?.id===item.id?'selected':''} onClick={()=>setActiveImage(item.id)}><FileImage size={15}/><span>{item.name}</span>{item.savedId&&!item.dirty?<CheckCircle2 className="tab-check" size={13}/>:<span className={'tab-state '+(item.criterion?'ready':'')}>{String(i+1).padStart(2,'0')}</span>}</button><button className="tab-delete" aria-label={'删除图片：'+item.name} title="删除图片" disabled={busy||saving||uploading} onClick={()=>removeImage(item)}><X size={14}/></button></div>)}</div>
 {current&&<div className="description-layout" role="tabpanel"><section className="panel image-panel"><div className="image-panel-title"><span><FileImage size={16}/>{current.name}</span><span>{batch.findIndex(i=>i.id===current.id)+1} / {batch.length}</span></div><div className="image-preview"><img src={current.image} alt={current.name}/></div><div className="image-bottom">{current.sourceURL?<a href={current.sourceURL} target="_blank" rel="noreferrer"><Globe2 size={14}/>{new URL(current.sourceURL).hostname}<ExternalLink size={12}/></a>:<span>{current.sample?'演示图片':'上传的图片'}</span>}<button className="text-button subtle" disabled={busy||saving} onClick={()=>removeImage(current)}>删除这张图片</button></div></section>
 <section className="panel description-editor"><div className="editor-heading"><span className="step-number">2</span><h2>背景与图片描述</h2>{current.savedId&&!current.dirty&&<span className="ready-badge"><Check size={13}/>已保存</span>}</div><label>材料类别 <span className="required">*</span><select aria-label="材料类别" value={current.criterion} onChange={e=>patchCurrent({criterion:e.target.value})} disabled={busy||saving}><option value="">请选择材料类别</option>{CRITERIA.map(c=><option key={c} value={c}>{criterionLabel(c)}</option>)}</select></label><label>申请人是否在画面中？ <span className="required">*</span><select aria-label="申请人是否在画面中？" value={current.applicantInImage||''} onChange={e=>patchCurrent({applicantInImage:e.target.value})} disabled={busy||saving}><option value="">请选择</option><option value="yes">是</option><option value="no">否</option><option value="unknown">不确定</option></select></label><p className="field-hint">如果选择“是”，请在备注中说明申请人的位置或特征；选择“否”或“不确定”时，不会默认把画面人物当作申请人。</p><label>背景备注 <span className="optional">选填</span><textarea aria-label="背景备注" rows={3} value={current.context} onChange={e=>patchCurrent({context:e.target.value})} disabled={busy||saving} placeholder="请补充申请人与图片的关系、活动名称、时间、职责等已确认的信息…"/></label><div className="description-divider"/><div className="description-label"><label htmlFor="description-text">英文描述</label><span>{current.description?'可直接修改':'等待生成'}</span></div><textarea id="description-text" className="description-text" rows={8} value={current.description} onChange={e=>patchCurrent({description:e.target.value})} disabled={busy||saving} placeholder="英文描述会显示在这里，也可以自行填写或修改。"/><label className="bilingual-label" htmlFor="description-zh">中文描述</label><textarea id="description-zh" className="description-text" rows={6} value={current.descriptionZh||''} onChange={e=>patchCurrent({descriptionZh:e.target.value})} disabled={busy||saving} placeholder="中文描述会显示在这里，可直接修改。"/>{current.error&&<div className="alert error">{current.error}</div>}<div className="word-count"><span>中英文可分别编辑，请核实内容并保持两种语言一致。</span><span>{current.description.trim()?current.description.trim().split(/\s+/).length:0} 个英文单词</span></div><div className="editor-actions"><button className="button" onClick={()=>copy('en')} disabled={!current.description||busy}><Copy size={15}/>复制英文</button><button className="button" onClick={()=>copy('zh')} disabled={!current.descriptionZh||busy}><Copy size={15}/>复制中文</button><button className="button primary" onClick={save} disabled={!current.description.trim()||!current.criterion||!current.applicantInImage||busy||saving||(current.savedId&&!current.dirty)}>{saving?<Loader2 size={16} className="spin"/>:<Save size={16}/>} {saving?'正在保存…':current.savedId?'保存修改':'保存'}</button></div>{current.savedId&&<button className="saved-link" onClick={()=>go('applicant/'+selected)}>查看 {applicant?.name} 的已保存材料<ArrowUpRight size={14}/></button>}</section></div>}
 </>:<section className="panel description-empty"><div className="empty-state"><span className="empty-icon"><Images size={29}/></span><h3>添加图片，开始整理材料</h3><p>上传图片并补充背景，生成描述后<br/>请逐张检查并保存。</p><div className="workflow-steps"><span><b>1</b>上传图片</span><ArrowRight size={15}/><span><b>2</b>补充背景</span><ArrowRight size={15}/><span><b>3</b>检查并保存</span></div></div></section>}</>;
}

function EvidenceEditor({evidence,onClose,onSaved,notify}){const [draft,setDraft]=useState({...evidence,savedId:evidence.id});const [busy,setBusy]=useState(false);const [dirty,setDirty]=useState(false);function update(p){setDraft(d=>({...d,...p}));setDirty(true);}return <Modal wide title="已保存材料" onClose={onClose}><div className="saved-editor-layout"><div className="saved-editor-image"><img src={evidence.image} alt={evidence.name}/><div><FileImage size={15}/>{evidence.name}</div></div><div className="saved-editor-fields"><div className="saved-owner"><span className="avatar small tone-0">{initials(evidence.applicantName)}</span><span>{evidence.applicantName}<small>{evidence.visaType} · {evidence.occupation}</small></span></div><label>材料类别<select aria-label="已保存材料类别" value={draft.criterion} onChange={e=>update({criterion:e.target.value})} disabled={busy}>{CRITERIA.map(c=><option key={c} value={c}>{criterionLabel(c)}</option>)}</select></label><label>英文描述<textarea aria-label="已保存的英文描述" rows={10} value={draft.description} onChange={e=>update({description:e.target.value})} disabled={busy}/></label><label>中文描述<textarea aria-label="已保存的中文描述" rows={7} value={draft.descriptionZh||''} onChange={e=>update({descriptionZh:e.target.value})} disabled={busy} placeholder="旧材料可能没有中文描述，可以在这里补充。"/></label><label>申请人是否在画面中？<select value={draft.applicantInImage||'unknown'} onChange={e=>update({applicantInImage:e.target.value})} disabled={busy}><option value="yes">是</option><option value="no">否</option><option value="unknown">不确定</option></select></label>{evidence.sourceURL&&<a className="source-link" href={evidence.sourceURL} target="_blank" rel="noreferrer"><Globe2 size={14}/>{new URL(evidence.sourceURL).hostname}<ExternalLink size={13}/></a>}<div className="saved-timestamp">创建于 {dateLabel(evidence.createdAt)}</div><div className="modal-footer"><button className="button" onClick={onClose}>关闭</button><button className="button primary" disabled={!dirty||!draft.description.trim()||busy} onClick={async()=>{setBusy(true);try{await request('/api/evidence',draft,'PUT');await onSaved();setDirty(false);}catch(e){notify(e.message,'error');}finally{setBusy(false);}}}>{busy?<Loader2 className="spin" size={16}/>:<Save size={16}/>}保存修改</button></div></div></div></Modal>;}
createRoot(document.getElementById('root')).render(<App/>);
