import React, { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowUpRight, ArrowRight, ArrowLeft, Plus, Users, Globe2, Images, Search, Check, X, Copy, UploadCloud, Sparkles, FileImage, CheckCircle2, Loader2, Menu, FolderOpen, ExternalLink, Save, Info, Bell, Settings } from 'lucide-react';
import './reference.css';

const CRITERIA = ['Critical Role','Media Coverage','Key Position','Commercial Success','Recommendation Letters','High Salary'];
const criterionNotes = ['Lead or featured participation','Published coverage of the work','An essential role in an organization','Documented commercial results','Recognition from industry experts','Compensation for professional work'];
async function request(url, data, method='POST') {const r=await fetch(url,data?{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}:{});const result=await r.json();if(!r.ok)throw new Error(result.error||'Something went wrong. Please try again.');return result;}
const initials = name => name.split(' ').map(x=>x[0]).slice(0,2).join('');
const dateLabel = value => new Date(value).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'});

function App(){
  const [state,setState]=useState({applicants:[],evidence:[],services:{ai:'demo',storage:'local'}});
  const [route,setRoute]=useState(location.hash.slice(1)||'applicants');
  const [selected,setSelected]=useState('');
  const [search,setSearch]=useState('');
  const [createOpen,setCreateOpen]=useState(false);
  const [toast,setToast]=useState(null);
  const [mobileOpen,setMobileOpen]=useState(false);
  const [loading,setLoading]=useState(true);
  const [error,setError]=useState('');
  const [batch,setBatch]=useState([]);
  const [activeImage,setActiveImage]=useState('');
  const [shot,setShot]=useState(null);
  const [detailFilter,setDetailFilter]=useState('All evidence');
  const [editing,setEditing]=useState(null);
  const [infoOpen,setInfoOpen]=useState('');
  const toastTimer=useRef();
  function notify(message,type='success'){setToast({message,type});clearTimeout(toastTimer.current);toastTimer.current=setTimeout(()=>setToast(null),5000);}
  async function refresh(){try{setState(await request('/api/state'));setError('');}catch(e){setError(e.message);}finally{setLoading(false);}}
  useEffect(()=>{refresh();const handler=()=>{setRoute(location.hash.slice(1)||'applicants');setMobileOpen(false);};window.addEventListener('hashchange',handler);return()=>window.removeEventListener('hashchange',handler);},[]);
  function go(next){location.hash=next;setRoute(next);setMobileOpen(false);window.scrollTo(0,0);}
  const applicant=state.applicants.find(a=>a.id===selected);
  const detailId=route.startsWith('applicant/')?route.split('/')[1]:null;
  const detail=state.applicants.find(a=>a.id===detailId);
  const pageName=route==='screenshot'?'Web Screenshot':route==='description'?'Image Description':detail?'Applicant profile':'Applicants';
  function openApplicant(a){setSelected(a.id);setDetailFilter('All evidence');go('applicant/'+a.id);}
  function chooseApplicant(id){setSelected(id);setBatch([]);setActiveImage('');setShot(null);}
  function toolFor(a,target){if(selected!==a.id)chooseApplicant(a.id);go(target);}
  const shared={state,applicant,selected,chooseApplicant,notify,refresh,setState};
  return <div className="app-shell">
    <aside className={'sidebar '+(mobileOpen?'open':'')}>
      <a className="brand" href="#applicants" onClick={()=>setMobileOpen(false)}><span>Visa Assistant<small>Internal Workbench</small></span></a>
      <nav><button className={route.startsWith('applicant')?'active':''} onClick={()=>go('applicants')}><Users size={18}/>Applicants</button>
      <button className={route==='screenshot'?'active':''} onClick={()=>go('screenshot')}><Globe2 size={19}/>URL Screenshot</button>
      <button className={route==='description'?'active':''} onClick={()=>go('description')}><Images size={19}/>Image Description</button></nav>
    </aside>
    {mobileOpen&&<div className="scrim" onClick={()=>setMobileOpen(false)}/>}
    <div className="main-shell"><header className="topbar"><button className="icon-button mobile-menu" aria-label="Toggle navigation" onClick={()=>setMobileOpen(!mobileOpen)}><Menu size={20}/></button><a className="topbar-brand" href="#applicants">Visa Assistant</a><div className="top-right"><button className="icon-button" aria-label="Notifications" onClick={()=>setInfoOpen('notifications')}><Bell size={20}/></button><button className="icon-button" aria-label="Settings" onClick={()=>setInfoOpen('settings')}><Settings size={20}/></button><span className="avatar tiny">JW</span></div></header>
    <main>
      {error&&<div className="alert error">{error}<button onClick={refresh}>Retry</button></div>}
      {loading?<div className="loading-page"><Loader2 className="spin"/>Opening your workspace…</div>:<>
      {route==='applicants'&&<>
        <div className="page-heading"><h1>申请人</h1><button className="button primary" onClick={()=>setCreateOpen(true)}>新建申请人</button></div>
        <div className="applicants-search search-input"><Search size={18}/><input aria-label="搜索申请人" placeholder="搜索申请人..." value={search} onChange={e=>setSearch(e.target.value)}/></div>
        <section className="panel applicants-panel"><div className="table-scroll"><table><thead><tr><th>姓名</th><th>签证类型</th><th>职业</th></tr></thead><tbody>{state.applicants.filter(a=>(a.name+' '+a.occupation).toLowerCase().includes(search.toLowerCase())).map(a=><tr key={a.id} onClick={()=>openApplicant(a)}><td><button className="person-link" onClick={e=>{e.stopPropagation();openApplicant(a);}}>{a.name}</button></td><td>{a.visaType}</td><td>{a.occupation}</td></tr>)}</tbody></table></div>{!state.applicants.some(a=>(a.name+' '+a.occupation).toLowerCase().includes(search.toLowerCase()))&&<div className="empty-state"><Search/><h3>没有匹配的申请人</h3><p>请尝试其他姓名或职业。</p></div>}</section>
      </>}
      {detail&&<ApplicantDetail {...shared} detail={detail} filter={detailFilter} setFilter={setDetailFilter} go={go} toolFor={toolFor} onEdit={setEditing}/>}
      {route==='screenshot'&&<ScreenshotPage {...shared} shot={shot} setShot={setShot} onSend={()=>{if(batch.some(i=>i.id===shot.id)){setActiveImage(shot.id);go('description');return;}if(batch.length>=10){notify('This batch already has 10 images. Remove an image before adding another.','error');return;}const next={...shot,criterion:'',context:'',description:'',savedId:null};setBatch(prev=>[...prev,next]);setActiveImage(next.id);go('description');notify('Screenshot added. Choose a criterion to continue.');}}/>}
      {route==='description'&&<DescriptionPage {...shared} batch={batch} setBatch={setBatch} activeImage={activeImage} setActiveImage={setActiveImage} go={go}/>}
      {route!=='applicants'&&route!=='screenshot'&&route!=='description'&&!detail&&<div className="empty-state"><FolderOpen/><h2>Applicant not found</h2><button className="button" onClick={()=>go('applicants')}>Back to applicants</button></div>}
      </>}
    </main></div>
    {createOpen&&<CreateApplicant onClose={()=>setCreateOpen(false)} onCreate={async a=>{const created=await request('/api/applicants',a);await refresh();setCreateOpen(false);openApplicant(created);notify('Applicant created successfully.');}}/>}
    {editing&&<EvidenceEditor evidence={editing} onClose={()=>setEditing(null)} onSaved={async()=>{await refresh();notify('Evidence changes saved.');}} notify={notify}/>}
    {infoOpen&&<Modal title={infoOpen==='settings'?'Workspace settings':'Notifications'} onClose={()=>setInfoOpen('')}><div className="info-content">{infoOpen==='settings'?<><p><strong>Storage</strong><span>Local demo · saved on this computer</span></p><p><strong>AI descriptions</strong><span>{state.services.ai==='connected'?'Connected':'Demo drafts · AI not configured'}</span></p><p><strong>URL screenshots</strong><span>Live page capture</span></p></>:<p>No new notifications.</p>}</div></Modal>}
    {toast&&<div className={'toast '+toast.type} role="status">{toast.type==='error'?<Info size={19}/>:<CheckCircle2 size={19}/>}<span>{toast.message}</span><button aria-label="Dismiss notification" onClick={()=>setToast(null)}><X size={16}/></button></div>}
  </div>;
}

function Modal({title,onClose,children,wide=false}){const ref=useRef();useEffect(()=>{const prior=document.activeElement;ref.current.showModal();return()=>prior?.focus();},[]);return <dialog ref={ref} className={'modal '+(wide?'wide':'')} onCancel={onClose} onClick={e=>{if(e.target===ref.current)onClose();}}><div className="modal-header"><h2>{title}</h2><button className="icon-button" aria-label="Close dialog" onClick={onClose}><X size={21}/></button></div>{children}</dialog>;}
function CreateApplicant({onClose,onCreate}){const [busy,setBusy]=useState(false);const [error,setError]=useState('');return <Modal title="Create Applicant" onClose={onClose}><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const f=new FormData(e.currentTarget);await onCreate(Object.fromEntries(f));}catch(e){setError(e.message);setBusy(false);}}}><p className="modal-intro">Add an applicant to organize their evidence and personalize descriptions.</p><label>Full name <span className="required">*</span><input autoFocus required name="name" maxLength={100} placeholder="e.g. Taylor Smith"/></label><label>Visa type <span className="required">*</span><select name="visaType" defaultValue="O1B"><option>O1B</option><option disabled>O2B</option><option disabled>O3B</option></select></label><label>Occupation <span className="required">*</span><input required name="occupation" maxLength={100} placeholder="e.g. Musician, Visual Artist"/></label>{error&&<div className="alert error">{error}</div>}<div className="modal-footer"><button type="button" className="button" onClick={onClose}>Cancel</button><button disabled={busy} className="button primary">{busy?<Loader2 className="spin" size={17}/>:<Plus size={17}/>}Create Applicant</button></div></form></Modal>;}

function ApplicantSelect({state,selected,chooseApplicant,disabled=false}){const a=state.applicants.find(x=>x.id===selected);return <div className="applicant-context"><label className="applicant-select-label">APPLICANT <span className="required">*</span><select aria-label="Applicant" value={selected} onChange={e=>chooseApplicant(e.target.value)} disabled={disabled}><option value="">Select an applicant</option>{state.applicants.map(a=><option key={a.id} value={a.id}>{a.name} ({a.visaType} · {a.occupation})</option>)}</select></label>{a?<div className="context-profile"><span className="avatar small tone-0">{initials(a.name)}</span><span>{a.occupation}<small>{a.visaType} application</small></span></div>:<span className="context-hint">Select who this evidence belongs to.</span>}</div>;}
function ApplicantDetail({state,detail,filter,setFilter,go,toolFor,onEdit}){
 const all=state.evidence.filter(e=>e.applicantId===detail.id);const items=all.filter(e=>filter==='All evidence'||e.criterion===filter);
 return <><button className="back-link" onClick={()=>go('applicants')}><ArrowLeft size={16}/>All applicants</button><div className="profile-heading"><div className="profile-identity"><span className="avatar large tone-0">{initials(detail.name)}</span><div><div className="eyebrow">APPLICANT PROFILE</div><h1>{detail.name}</h1><div className="profile-meta"><span className="visa-badge">{detail.visaType}</span><span>{detail.occupation}</span><span className="meta-dot"/>Created {dateLabel(detail.createdAt)}</div></div></div><div className="button-group"><button className="button" onClick={()=>toolFor(detail,'screenshot')}><Globe2 size={16}/>Web Screenshot</button><button className="button primary" onClick={()=>toolFor(detail,'description')}><Plus size={17}/>Add evidence</button></div></div>
 <div className="section-heading"><h2>O1B evidence categories</h2><span>{all.length} saved materials across 6 criteria</span></div><div className="criteria-grid">{CRITERIA.map((c,i)=><button key={c} className={'criterion-card '+(filter===c?'selected':'')} onClick={()=>setFilter(filter===c?'All evidence':c)}><div><span className="criterion-number">0{i+1}</span><span className="count-badge">{all.filter(e=>e.criterion===c).length}</span></div><h3>{c}</h3><p>{criterionNotes[i]}</p></button>)}</div>
 <section className="panel evidence-panel"><div className="panel-toolbar"><div className="section-title">Saved Evidence <span className="count-badge">{all.length}</span></div><select aria-label="Filter saved evidence" className="compact-select" value={filter} onChange={e=>setFilter(e.target.value)}>{['All evidence',...CRITERIA].map(c=><option key={c}>{c}</option>)}</select></div>{items.length?<div className="evidence-grid">{items.map(e=><button className="evidence-card" key={e.id} onClick={()=>onEdit(e)}><div className="evidence-thumb"><img src={e.image} alt={e.name}/><span className="thumb-action">View & edit<ArrowUpRight size={15}/></span></div><div className="evidence-card-body"><span className="category-tag">{e.criterion}</span><h3>{e.name}</h3><p>{e.description}</p><div className="evidence-card-meta"><span>{e.sourceURL?new URL(e.sourceURL).hostname:'Uploaded image'}</span><span>{dateLabel(e.createdAt)}</span></div></div></button>)}</div>:<div className="empty-state"><span className="empty-icon"><FolderOpen size={28}/></span><h3>{filter==='All evidence'?'Your evidence starts here':'No evidence in this category yet'}</h3><p>Capture a web page or upload an image.<br/>Review its description, then save it to this applicant.</p><button className="button primary" onClick={()=>toolFor(detail,'description')}><Plus size={17}/>Add first evidence</button><span className="empty-footnote">Only materials you explicitly save appear here.</span></div>}</section></>;
}

function ScreenshotPage({state,selected,chooseApplicant,notify,shot,setShot,onSend}){
 const [url,setURL]=useState('');const [size,setSize]=useState('a4');const [width,setWidth]=useState(1200);const [height,setHeight]=useState(900);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [step,setStep]=useState(0);
 useEffect(()=>{if(!busy)return;setStep(0);const t=setInterval(()=>setStep(s=>Math.min(2,s+1)),1800);return()=>clearInterval(t);},[busy]);
 async function capture(sample=false){if(!selected){setError('Select an applicant before generating a screenshot.');return;}if(!sample){try{const u=new URL(url);if(!['http:','https:'].includes(u.protocol))throw new Error();}catch{setError('Enter a complete URL starting with https:// or http://.');return;}}setError('');setBusy(true);try{setShot(await request('/api/screenshot',{applicantId:selected,url,sample,width:size==='a4'?1200:width,height:size==='a4'?1697:height}));notify('Clean screenshot is ready.');}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function copyImage(){try{const blob=await(await fetch(shot.image)).blob();await navigator.clipboard.write([new ClipboardItem({'image/png':blob})]);notify('Image copied to clipboard.');}catch{notify('Image could not be copied. Allow clipboard access in your browser and try again.','error');}}
 return <><div className="page-heading"><div><div className="eyebrow">EVIDENCE TOOLS</div><h1>Web Screenshot</h1><p>Keep the content that matters. Turn a source page into clean evidence.</p></div><span className="feature-label"><Globe2 size={15}/>Live page capture</span></div><ApplicantSelect {...{state,selected,chooseApplicant}} disabled={busy}/>
 <div className="screenshot-layout"><section className="panel capture-controls"><div className="panel-section-heading"><span className="step-number">1</span><h2>Capture a page</h2></div><form onSubmit={e=>{e.preventDefault();capture();}}><label>Source URL <span className="required">*</span><div className="url-input"><Globe2 size={17}/><input aria-label="Source URL" type="url" placeholder="https://example.com/article" value={url} onChange={e=>setURL(e.target.value)} disabled={busy}/></div></label><p className="field-hint">A public article, publication, or video page.</p><label className="size-label">Screenshot size</label><div className="segmented" role="group" aria-label="Screenshot size"><button type="button" className={size==='a4'?'selected':''} onClick={()=>setSize('a4')} disabled={busy}>A4 portrait</button><button type="button" className={size==='custom'?'selected':''} onClick={()=>setSize('custom')} disabled={busy}>Custom</button></div>{size==='custom'?<div className="dimension-fields"><label>Width (px)<input aria-label="Width (px)" type="number" required min="480" max="1600" value={width} onChange={e=>setWidth(e.target.value)}/></label><span>×</span><label>Height (px)<input aria-label="Height (px)" type="number" required min="480" max="2000" value={height} onChange={e=>setHeight(e.target.value)}/></label></div>:<div className="size-caption">1200 × 1697 px <span>Fixed canvas</span></div>}{error&&<div className="alert error" role="alert">{error}</div>}<button className="button primary full-width" disabled={busy||!selected||!url.trim()}>{busy?<Loader2 size={17} className="spin"/>:<Sparkles size={17}/>} {busy?'Preparing screenshot…':'Generate Screenshot'}</button></form><div className="sample-cta"><span>Explore with a sample</span><p>Try a fictional music article to see the complete workflow.</p><button className="text-button" disabled={busy||!selected} onClick={()=>capture(true)}>Use sample article<ArrowRight size={15}/></button></div><div className="capture-note"><CheckCircle2 size={16}/><div><strong>Focused on the main content</strong><p>Headers, navigation, sidebars, ads, and recommendations are removed.</p></div></div></section>
 <section className="panel capture-preview"><div className="panel-toolbar"><div className="section-title"><span className="step-number">2</span>Clean preview</div>{shot&&!busy&&<span className="ready-badge"><Check size={13}/>Ready</span>}</div><div className={'screenshot-canvas '+(shot?'has-image':'')}>{busy?<div className="capture-loading"><span className="loading-orbit"><Globe2 size={30}/></span><h3>{['Reading the page','Finding the main content','Preparing the clean canvas'][step]}</h3><p>This can take a few moments.</p><div className="progress-track"><span style={{width:[25,58,87][step]+'%'}}/></div></div>:shot?<img className="shot-image" src={shot.image} alt={'Clean screenshot: '+shot.title}/>:<div className="empty-state"><span className="page-outline"><span/><span/><span/><span/></span><h3>A cleaner view of your source</h3><p>Your screenshot will appear here,<br/>ready to copy or send for a description.</p><div className="preview-tags"><span>Title & metadata</span><span>Main content</span><span>Key media</span></div></div>}</div>{shot&&!busy&&<><div className="shot-meta"><FileImage size={16}/><div><strong>{shot.name}</strong><span>{shot.width} × {shot.height} px · PNG{shot.sample?' · Demo sample':''}</span></div></div><div className="preview-actions"><button className="button" onClick={copyImage}><Copy size={16}/>Copy Image</button><button className="button primary" onClick={onSend}>Send to Image Description<ArrowRight size={16}/></button></div></>}</section></div></>;
}

function DescriptionPage({state,applicant,selected,chooseApplicant,notify,refresh,batch,setBatch,activeImage,setActiveImage,go}){
 const [busy,setBusy]=useState(false);const [uploading,setUploading]=useState(false);const [saving,setSaving]=useState(false);const [error,setError]=useState('');const [dragging,setDragging]=useState(false);const inputRef=useRef();
 const current=batch.find(i=>i.id===activeImage)||batch[0];const ready=batch.filter(i=>i.criterion).length;const generated=batch.filter(i=>i.description).length;
 function patchCurrent(patch){setBatch(items=>items.map(i=>i.id===current.id?{...i,...patch,dirty:true}:i));}
 async function upload(files){if(!selected)return setError('Select an applicant before uploading images.');const list=Array.from(files);if(!list.length)return;if(batch.length+list.length>10)return setError('Upload up to 10 images per batch.');if(list.some(f=>!['image/jpeg','image/png','image/webp'].includes(f.type)))return setError('Use PNG, JPG, or WebP images.');if(list.some(f=>f.size>8*1024*1024))return setError('Each image must be smaller than 8 MB.');setError('');setUploading(true);try{const added=await Promise.all(list.map(file=>new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>{const img=new Image();img.onload=()=>resolve({id:crypto.randomUUID(),name:file.name,image:reader.result,criterion:'',context:'',description:'',sourceURL:'',savedId:null,dirty:true});img.onerror=()=>reject(new Error(file.name+' is not a readable image.'));img.src=reader.result;};reader.onerror=()=>reject(new Error('Could not read '+file.name));reader.readAsDataURL(file);})));setBatch(items=>[...items,...added]);setActiveImage(added[0].id);notify(`${added.length} image${added.length>1?'s':''} added. Choose a criterion for each.`);}catch(e){setError(e.message);}finally{setUploading(false);if(inputRef.current)inputRef.current.value='';}}
 async function generate(){setError('');if(!selected||!batch.length||ready!==batch.length)return setError('Select an applicant and a criterion for every image.');setBusy(true);try{const result=await request('/api/describe',{applicantId:selected,images:batch});setBatch(items=>items.map(item=>{const r=result.results.find(x=>x.id===item.id);return r?.description?{...item,description:r.description,dirty:true,error:null}:{...item,error:r?.error};}));const failed=result.results.filter(r=>r.error).length;if(failed)setError(`${failed} description(s) could not be generated. Select each image to review its error and retry.`);else notify('All descriptions are ready to review.');}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function save(){setSaving(true);try{const saved=await request('/api/evidence',{...current,applicantId:selected},current.savedId?'PUT':'POST');setBatch(items=>items.map(i=>i.id===current.id?{...i,savedId:saved.id,dirty:false}:i));await refresh();notify('Evidence saved to '+applicant.name+'.');}catch(e){notify(e.message,'error');}finally{setSaving(false);}}
 async function copy(){try{await navigator.clipboard.writeText(current.description);notify('Description copied.');}catch{notify('Could not access the clipboard. Select and copy the description manually.','error');}}
 return <><div className="page-heading"><div><div className="eyebrow">EVIDENCE TOOLS</div><h1>Image Description</h1><p>Give every image the right context. Review each description before saving.</p></div><span className="feature-label"><Images size={15}/>Multi-image workspace</span></div><ApplicantSelect {...{state,selected,chooseApplicant}} disabled={busy||saving||uploading}/>
 <section className="panel upload-panel"><div className="upload-heading"><div className="section-title"><span className="step-number">1</span>Add your images</div><span>PNG, JPG, WebP · Up to 8 MB each</span></div><input ref={inputRef} className="visually-hidden" type="file" multiple accept="image/png,image/jpeg,image/webp" aria-label="Upload images" onChange={e=>upload(e.target.files)} disabled={!selected||busy||uploading}/><button className={'dropzone '+(dragging?'dragging':'')} disabled={!selected||busy||uploading} onClick={()=>inputRef.current.click()} onDragOver={e=>{e.preventDefault();setDragging(true);}} onDragLeave={()=>setDragging(false)} onDrop={e=>{e.preventDefault();setDragging(false);if(!busy&&!uploading)upload(e.dataTransfer.files);}}><span className="upload-icon">{uploading?<Loader2 className="spin" size={23}/>:<UploadCloud size={25}/>}</span><span><strong>{!selected?'Select an applicant to add images':uploading?'Adding your images…':'Click to upload'}{selected&&!uploading&&<em> or drag and drop</em>}</strong><small>{selected?'Add up to 10 images. Each image has its own criterion and notes.':'Your images and descriptions will be linked to this applicant.'}</small></span>{selected&&<span className="button upload-browse">Browse files</span>}</button><div className="generation-toolbar"><div>{batch.length?<><strong>{batch.length} image{batch.length>1?'s':''} added</strong><span>{ready} of {batch.length} criteria selected{generated?' · '+generated+' descriptions ready':''}</span></>:<span>Select a criterion for every image, then generate all descriptions.</span>}</div><button className="button primary" onClick={generate} disabled={busy||uploading||saving||!batch.length||ready!==batch.length||!selected}>{busy?<Loader2 size={17} className="spin"/>:<Sparkles size={17}/>} {busy?'Generating descriptions…':'Generate Descriptions for All'}</button></div></section>
 {state.services.ai==='demo'&&<div className="demo-banner"><Info size={16}/><span>Demo mode: drafts use supplied context and captured text. Visual AI is not connected.</span></div>}{error&&<div className="alert error" role="alert">{error}</div>}
 {batch.length>0?<><div className="image-tabs" role="tablist" aria-label="Uploaded images">{batch.map((item,i)=><button key={item.id} role="tab" aria-selected={current?.id===item.id} className={current?.id===item.id?'selected':''} onClick={()=>setActiveImage(item.id)}><FileImage size={15}/><span>{item.name}</span>{item.savedId&&!item.dirty?<CheckCircle2 className="tab-check" size={13}/>:<span className={'tab-state '+(item.criterion?'ready':'')}>{String(i+1).padStart(2,'0')}</span>}</button>)}</div>
 {current&&<div className="description-layout" role="tabpanel"><section className="panel image-panel"><div className="image-panel-title"><span><FileImage size={16}/>{current.name}</span><span>{batch.findIndex(i=>i.id===current.id)+1} / {batch.length}</span></div><div className="image-preview"><img src={current.image} alt={current.name}/></div><div className="image-bottom">{current.sourceURL?<a href={current.sourceURL} target="_blank" rel="noreferrer"><Globe2 size={14}/>{new URL(current.sourceURL).hostname}<ExternalLink size={12}/></a>:<span>{current.sample?'Demo sample image':'Uploaded image'}</span>}<button className="text-button subtle" disabled={busy||saving} onClick={()=>{const remaining=batch.filter(i=>i.id!==current.id);setBatch(remaining);setActiveImage(remaining[0]?.id||'');}}>Remove from batch</button></div></section>
 <section className="panel description-editor"><div className="editor-heading"><span className="step-number">2</span><h2>Context & description</h2>{current.savedId&&!current.dirty&&<span className="ready-badge"><Check size={13}/>Saved</span>}</div><label>O1B Criterion <span className="required">*</span><select aria-label="O1B Criterion" value={current.criterion} onChange={e=>patchCurrent({criterion:e.target.value})} disabled={busy||saving}><option value="">Select a criterion</option>{CRITERIA.map(c=><option key={c}>{c}</option>)}</select></label><label>Context / Notes <span className="optional">Optional</span><textarea aria-label="Context / Notes" rows={3} value={current.context} onChange={e=>patchCurrent({context:e.target.value})} disabled={busy||saving} placeholder="Add an event, role, date, or outcome that this image supports…"/></label><div className="description-divider"/><div className="description-label"><label htmlFor="description-text">{state.services.ai==='demo'?'Description':'AI Description'}</label><span>{current.description?'Editable draft':'Awaiting generation'}</span></div><textarea id="description-text" className="description-text" rows={8} value={current.description} onChange={e=>patchCurrent({description:e.target.value})} disabled={busy||saving} placeholder="Your English description will appear here. You can also write or edit it yourself."/>{current.error&&<div className="alert error">{current.error}</div>}<div className="word-count"><span>Review names, context, and facts before saving.</span><span>{current.description.trim()?current.description.trim().split(/\s+/).length:0} words</span></div><div className="editor-actions"><button className="button" onClick={copy} disabled={!current.description||busy}><Copy size={15}/>Copy</button><button className="button primary" onClick={save} disabled={!current.description.trim()||!current.criterion||busy||saving||(current.savedId&&!current.dirty)}>{saving?<Loader2 size={16} className="spin"/>:<Save size={16}/>} {saving?'Saving…':current.savedId?'Save Changes':'Save'}</button></div>{current.savedId&&<button className="saved-link" onClick={()=>go('applicant/'+selected)}>View in {applicant?.name}'s Saved Evidence<ArrowUpRight size={14}/></button>}</section></div>}
 </>:<section className="panel description-empty"><div className="empty-state"><span className="empty-icon"><Images size={29}/></span><h3>Every image tells part of the story</h3><p>Upload images, add their context, then review<br/>and save each description individually.</p><div className="workflow-steps"><span><b>1</b>Upload</span><ArrowRight size={15}/><span><b>2</b>Add context</span><ArrowRight size={15}/><span><b>3</b>Review & save</span></div></div></section>}</>;
}

function EvidenceEditor({evidence,onClose,onSaved,notify}){const [draft,setDraft]=useState({...evidence,savedId:evidence.id});const [busy,setBusy]=useState(false);const [dirty,setDirty]=useState(false);function update(p){setDraft(d=>({...d,...p}));setDirty(true);}return <Modal wide title="Saved Evidence" onClose={onClose}><div className="saved-editor-layout"><div className="saved-editor-image"><img src={evidence.image} alt={evidence.name}/><div><FileImage size={15}/>{evidence.name}</div></div><div className="saved-editor-fields"><div className="saved-owner"><span className="avatar small tone-0">{initials(evidence.applicantName)}</span><span>{evidence.applicantName}<small>{evidence.visaType} · {evidence.occupation}</small></span></div><label>O1B Criterion<select aria-label="Saved evidence criterion" value={draft.criterion} onChange={e=>update({criterion:e.target.value})} disabled={busy}>{CRITERIA.map(c=><option key={c}>{c}</option>)}</select></label><label>Description<textarea aria-label="Saved evidence description" rows={10} value={draft.description} onChange={e=>update({description:e.target.value})} disabled={busy}/></label>{evidence.sourceURL&&<a className="source-link" href={evidence.sourceURL} target="_blank" rel="noreferrer"><Globe2 size={14}/>{new URL(evidence.sourceURL).hostname}<ExternalLink size={13}/></a>}<div className="saved-timestamp">Created {dateLabel(evidence.createdAt)}</div><div className="modal-footer"><button className="button" onClick={onClose}>Close</button><button className="button primary" disabled={!dirty||!draft.description.trim()||busy} onClick={async()=>{setBusy(true);try{await request('/api/evidence',draft,'PUT');await onSaved();setDirty(false);}catch(e){notify(e.message,'error');}finally{setBusy(false);}}}>{busy?<Loader2 className="spin" size={16}/>:<Save size={16}/>}Save Changes</button></div></div></div></Modal>;}
createRoot(document.getElementById('root')).render(<App/>);
